newsapp/urls.py
from django.urls import path
from .views import *


app_name="newsapp"
urlpatterns=[
path("",HomeView.as_view(), name="home"),
path("category/<int:pk>/detail",CategoryDetailView.as_view(),name="categorydetail"),
path("news/<int:pk>/newsdetail/",NewsDetailView.as_view(), name="newsdetail"),
path("contact/create/",ContactCreateView.as_view(), name="contactcreate"),


path("news-admin/category/create/",CategoryCreateView.as_view(), name="categorycreate"),

path("news-admin/news/create/",NewsCreateView.as_view(), name="newscreate"),

path("subscriber/",SubscriberCreateView.as_view(),name="subscriber"),





]

newsproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('newsapp.urls')),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

newsapp/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
	title=models.CharField(max_length=200)
	image=models.ImageField(upload_to="category")
	
	def __str__(self):
		return self.title

		#manayto one relation in category and news
class News(models.Model):
	title=models.CharField(max_length=300)
	category=models.ForeignKey(Category,on_delete=models.CASCADE)
	image=models.ImageField(upload_to="news")
	content=models.TextField()
	author=models.CharField(max_length=100,null=True,blank=True)
	date=models.DateTimeField(auto_now_add=True)
	view_count=models.PositiveIntegerField(default=0)
	
	def __str__(self):
		return self.title

class Comment(models.Model):
	name=models.CharField(max_length=200)
	news=models.ForeignKey(News,on_delete=models.CASCADE)
	text=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.name

class Contact(models.Model):
	name=models.CharField(max_length=200)
	address=models.CharField(max_length=200)
	contact=models.CharField(max_length=20)
	email=models.EmailField()
	def __str__(self):
		return self.name



class Subscriber(models.Model):
	email=models.EmailField()
	date=models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.email

newsapp/forms.py
from django import forms
from .models import *


class CategoryForm(forms.ModelForm):
	class Meta:
		model=Category
		fields=["title","image"]


class NewsForm(forms.ModelForm):
	class Meta:
		model=News
		fields=["title","category","image","content","author"]


class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields=["name","news","text"]


class ContactForm(forms.ModelForm):
	class Meta:
		model=Contact
		fields=["name","address","contact","email"]

class SubscriberForm(forms.ModelForm):
	class Meta:
		model=Subscriber
		fields=["email"]

newsapp/views.py
from django.conf import settings
from django.core.mail import send_mail

from django.shortcuts import render
from django.views.generic import *
from .forms import *

from .models import *
import requests


class BaseMixin(object):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["allcats"] = Category.objects.all()
        context["subsform"] = SubscriberForm
        return context


class HomeView(BaseMixin, TemplateView):
    template_name = "home.html"


class CategoryDetailView(BaseMixin, DetailView):
    template_name = "categorydetail.html"
    model = Category
    context_object_name = "categoryobject"


class NewsDetailView(BaseMixin, DetailView):
    template_name = "newsdetail.html"
    model = News
    context_object_name = "newsobject"


class CategoryCreateView(BaseMixin, CreateView):
    template_name = "categorycreate.html"
    form_class = CategoryForm
    success_url = "/"


class NewsCreateView(BaseMixin, CreateView):
    template_name = "newscreate.html"
    form_class = NewsForm
    success_url = "/"

    def form_valid(self, form):
        a = form.cleaned_data["title"]
        b = form.cleaned_data["category"]
        print(a, b)

        return super().form_valid(form)


class ContactCreateView(BaseMixin, CreateView):
    template_name = "contactcreate.html"
    form_class = ContactForm
    success_url = "/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        response = requests.get(
            "https://ratopati.com/jsonapi/get_recent_posts/")
        results = eval(response.text)
        results = results['posts']
        context['allarticles'] = results
        return context

    def form_valid(self, form):
        form_name = form.cleaned_data["name"]
        form_email = form.cleaned_data["email"]

        subject = 'Site contact form'
        from_email = settings.EMAIL_HOST_USER
        contact_message = "Thanks for contacting us."
        send_mail(subject,
                  contact_message,
                  from_email,
                  [form_email],
                  fail_silently=False)
        return super().form_valid(form)


class SubscriberCreateView(BaseMixin, CreateView):
    template_name = "subscriber.html"
    form_class = SubscriberForm
    success_url = "/"

    def form_valid(self, form):

        form_email = form.cleaned_data["email"]

        subject = 'Site contact form'
        from_email = settings.EMAIL_HOST_USER
        contact_message = "Thanks for subscribing us."
        send_mail(subject,
                  contact_message,
                  from_email,
                  [form_email],
                  fail_silently=False)
        return super().form_valid(form)
    # def get_context_data(self,**kwargs):
    # 	context=super().get_context_data(**kwargs)
    # 	context["subsform"]=SubscriberForm
    # 	return context


# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title> </title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">



</head>
<body class="container-fluid">
 <div id="fb-root">

 </div>
 <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3">

 </script>




 <nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <a class="navbar-brand" href="{% url 'newsapp:home' %}">isharaNewssite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'newsapp:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'newsapp:contactcreate' %}">Contact <span class="sr-only">(current)</span></a>
      </li>
      {% for category in allcats %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'newsapp:categorydetail' category.id %}">{{category.title}}</a>
      </li>
      {% endfor %}


      <li class="nav-item dropdown">



        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Category
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <a class="dropdown-item" href="#"></a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>


      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>



{% block content %}
{% endblock %}
<div class="row">
  <div class="col-md-4">
    <form method="POST" action="{% url 'newsapp:subscriber' %}">
      {% csrf_token %}
      {{subsform.as_p}}
      <button class="btn btn-success">Subscribe us</button>
      
    </form>
    
  </div>
</div>

</body>
</html>

templates/categorycreate.html
{%  extends "base.html" %}
{% block content %}


<div class="row">
	<div class="col-md-4 mx-auto">
	<h4>Add new category</h4>
	 <form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-info btn-block">Submit</button>
	
</form>
	</div>
</div>




{% endblock %}

templates/categorydetail.html
{%  extends "base.html" %}
{% block content %}
<h3 style="text-align: center;">Welcome to Category</h3>

<h3>News under {{categoryobject}}</h3>
{% for news in categoryobject.news_set.all %}
<!-- <h4>{{news.title}}</h4> -->

<h4>Title:{{news.title}}</h4> 

<img src="{{news.image.url}}" width="500">
<a href="{% url 'newsapp:newsdetail' news.id %}">View detail</a>

<!-- <a href="/news/{{news.id}}/newsdetail/"> view detail</a> -->

{% endfor %}

{% endblock %}

templates/contactcreate.html
{%  extends "base.html" %}
{% block content %}


<div class="row">
	<div class="col-md-6">
		<h4>Add new news</h4>
		<form method="POST" enctype="multipart/form-data" action=" " >
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info btn-block">Submit</button>
			
		</form>
	</div>
	<div class="col-md-6">
		{% for article in allarticles %}
		<div class="row">
			<div class="col-md-6">
				<h4>{{article.title}}</h4>
				<p>{{article.content|safe}}</p>
			</div>
			<div class="col-md-6">
				<img src="{{article.title_photo}}" class="img-fluid" style="height: 100px;">
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/home.html
	{%  extends "base.html" %}
	{% block content %}
	<div class="row">
		<div class="col-md-8">
			{% for category in allcats %}
			<h3>{{category.title}}</h3><hr>
			<div class="row">
				{% for news in category.news_set.all|slice:"6" %}
				<div class="col-md-4">
					<h4>{{news.title}}</h4>
					<img src="{{news.image.url}}" class="img-fluid">
					<p>{{news.content|truncatewords:"15"}}</p>
				</div>
				{% endfor %}
			</div>

			{% endfor %}

		</div>
		<div class="col-md-4">

		</div>
	</div>



	{% endblock %}

templates/newscreate.html
{%  extends "base.html" %}
{% block content %}


<div class="row">
	<div class="col-md-4 mx-auto">
		<h4>Add new news</h4>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info btn-block">Submit</button>
			
		</form>
	</div>
</div>
{% endblock %}

templates/newsdetail.html
	{%  extends "base.html" %}
	{% block content %}


	{% if newsobject.image %}
	<img src="{{newsobject.image.url}}" alt="Avatar" width=550px; >

	<h2><b>{{newsobject.title}}</b></h2>	
	<h4>{{newsobject.content}}</h4>
	<p>Author:{{newsobject.author}}</p>
	<p>Date:{{newsobject.date}}</p>
	<p>viewcount:{{newsobject.view_count}}</p>


	{% endif %}
	{% endblock %}